"""create products table

Revision ID: e0faaded3e73
Revises: debbfea969ff
Create Date: 2026-06-09 21:50:11.215925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0faaded3e73'
down_revision: Union[str, Sequence[str], None] = 'debbfea969ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty_per_box', sa.Integer(), nullable=False),
    sa.Column('exworks_price', sa.Numeric(), nullable=False),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shipping_route', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('exworks_price >= 0', name='check_exworks_price_non_negative'),
    sa.CheckConstraint('qty_per_box > 0', name='check_qty_per_box_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
